Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine318"
  
  MACHINES_COUNT = 3
  
  (1..MACHINES_COUNT).each do |i|
    config.vm.define "ALPINE-SFTP-#{i}" do |node|
      node.vm.hostname = "ALPINE-SFTP-#{i}"
      node.vm.network "public_network", ip: "192.168.0.10#{i}"
      
      node.vm.provider "virtualbox" do |vb|
        vb.memory = 256
        vb.cpus = 1
      end

      node.vm.provision "shell", path: "preconfig.sh"
    end
  end
end
